name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib numpy coverage
        # Install xvfb for headless Tkinter testing
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Run tests with coverage
      run: |
        # Ensure the sales_analysis_system module is discoverable for coverage
        mkdir -p sales_analysis_system
        cp main.py sales_analysis_system/
        cp test.py sales_analysis_system/

        # Run tests using xvfb-run to provide a virtual display for Tkinter
        xvfb-run -a python -m unittest -v sales_analysis_system/test.py
